import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 shadow sm:items-baseline w-full">
          <div className="mb-2 sm:mb-0">
            <Link
              href="/"
              className="text-2xl no-underline text-grey-darkest hover:text-blue-dark"
            >
              Home
            </Link>
          </div>
          <div>
            {/* <a
              href="#"
              className="text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2"
            >
              One
            </a> */}
          </div>
        </nav>
        <main className="mt-5">{children}</main>
      </body>
    </html>
  );
}
